"""The PyPSA ladder page, generated from what the parity runner committed.

    pixi run python -m tools.ladder           # rewrite docs/examples/pypsa_ladder.md
    pixi run python -m tools.ladder --check   # fail if it has drifted

Per rung: the file it binds, the tables the binding produced (the committed
CSVs under ``differential/pypsa/tables/``, embedded byte for byte), what the
relational lane built per block, and the verdicts from the certificate. The
network and the binding themselves are math-spec's, and each rung links to
them there. Nothing here runs pypsa: the runner wrote these files, and the
``PyPSA parity`` workflow holds them to what the corpus produces.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LADDER = ROOT / 'differential' / 'pypsa'
PAGE = ROOT / 'docs' / 'examples' / 'pypsa_ladder.md'
CORPUS_PAGE = 'https://math-spec.readthedocs.io/en/latest/examples/pypsa/'


def _tables(stem: str) -> str:
    return '\n\n'.join(
        f'`{path.name}`\n\n```csv\n{path.read_text().rstrip()}\n```'
        for path in sorted((LADDER / 'tables' / stem).glob('*.csv'))
    )


def _verdicts(record: dict) -> str:
    parity, structural = record['parity'], record['structural']
    prices = parity['prices']
    priced = f'prices agree on {prices["compared"]} rows' if prices['compared'] else f'no prices — {prices["skipped"]}'
    proof = (
        f'**model for model**: {len(structural["equal"])} blocks equal, {len(structural["region"])} documented splits'
        if 'equal' in structural
        else f'objective only — `lpspec.linopy` stops at `{structural["error"]}`'
    )
    return (
        f'> {"✔" if parity["matches"] else "✘"} lpspec solves `{parity["model"]}` bound to this network to '
        f"`{parity['lpspec_objective']}`, PyPSA's objective; {priced}; {proof}."
    )


def _tables_note(stem: str, record: dict) -> str:
    written = {path.stem for path in (LADDER / 'tables' / stem).glob('*.csv')}
    fed = set(record['parity']['bound_nonempty'])
    assert written <= fed, f'{stem}: a committed table is not stamped as bound non-empty'
    return (
        f'{len(fed)} tables bound non-empty, {len(written)} of them first fed by this rung and shown here; the rest'
        ' were first fed by a lower rung and grow with the network.'
    )


def _built(record: dict) -> str:
    rows = record['parity']['built_rows']
    lines = [f'| `{name}` | {count} |' for name, count in rows.items() if count]
    return '| block | rows built |\n| --- | ---: |\n' + '\n'.join(lines)


def rendered() -> str:
    stamped = json.loads((LADDER / 'references.json').read_text())
    parts = [
        '# The PyPSA ladder, as lpspec builds it\n',
        'Every rung of [the PyPSA corpus](' + CORPUS_PAGE + ') — the file, and the network as a PyPSA script'
        ' — is what math-spec states. This page is the other half: the binding, the tables it produces for'
        ' each rung, committed under `differential/pypsa/tables/` and held to the corpus by'
        ' the `PyPSA parity` workflow, the rows lpspec builds from them, and how deep the comparison with PyPSA'
        ' goes. `lps.solve(file, tables)` is the whole call.\n',
        '<!-- generated by tools/ladder.py from differential/pypsa — do not edit -->\n',
        '## The binding\n',
        'A network becomes the tables the file declares through `prep.py`: plain renames, and every parameter'
        ' the file marks "data prep" computed where it says so. It is the one piece of code between a PyPSA'
        ' network and `lps.solve`, and the tables under each rung are what it produced.\n',
        '<details markdown="1">\n<summary><code>differential/pypsa/prep.py</code></summary>\n\n'
        f'```python\n{(LADDER / "prep.py").read_text().rstrip()}\n```\n\n</details>\n',
    ]
    for stem in sorted(stamped):
        record = stamped[stem]
        number, _, title = stem.partition('_')[2].partition('_')
        parts.append(
            f'## Rung {int(number)} — {title.replace("_", " ")}\n\n'
            f'{_verdicts(record)}\n\n'
            f'The network: [`{stem}.py`]({CORPUS_PAGE}#rung-{int(number)}).\n\n'
            f'{_tables_note(stem, record)}\n\n'
            + (
                f'<details markdown="1">\n<summary>The tables this rung is the first to feed</summary>\n\n'
                f'{_tables(stem)}\n\n</details>\n\n'
                if _tables(stem)
                else ''
            )
            + f'<details markdown="1">\n<summary>What lpspec built</summary>\n\n{_built(record)}\n\n</details>\n'
        )
    return '\n'.join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='fail if the committed page has drifted')
    args = ap.parse_args(argv)
    text = rendered()
    if args.check:
        if PAGE.read_text() != text:
            print(f'{PAGE.relative_to(ROOT)} has drifted — pixi run python -m tools.ladder', file=sys.stderr)
            return 1
        return 0
    PAGE.write_text(text)
    print(f'wrote {PAGE.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
